public class DemoException{	public static void main(String [] o)	{		/** 				untuk menangkap exception kitaa guanakan try		catch untuk menangkap error		*/		try{			int [] angka={5,6};			System.out.println(angka[6]);			// System.out.println("tess");			int hasil=10/0;			// System.out.println("toss");			System.out.println(hasil);		}catch(ArrayIndexOutOfBoundsException el){			System.out.println("ADA ERROR ARRAY!!!");		}catch(ArithmeticException e2){			System.out.println("TERJADI BAGI 0!!!");		}catch(Exception ex){			System.out.println("Ada Error Mysterius..."+ex);			/**			untuk mendapatkan error yang lebih lengkap kita gunakan			ex.printStackTrace();			*/			// ex.printStackTrace();			System.out.println("block finally running....");		}		/**		finally = blok yg dijamin selalu running baik ada exception maupun tidak		*blok yang dijamin selalu jalan		*biar syntax lebih enak dibaca			*/		finally{			System.out.println("blok finally running");		}			}}